### ISSUE TITLE
Typo on your paper, Aggretriever (Conclusion)

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [castorini/dhr#1]
Hello, castorini!
I have read your paper with many interests.
While reading "Aggretriever: A Simple Approach to Aggregate Textual Representation for Robust Dense Passage Retrieval", I found one tiny typo in your conclusion section.
On the left top of page 10, the pdf that you have published on Arxiv, there is a sentence written as below.
> on MLM task while fine-tuning for DRP, and we

I think the "DRP" should be written as "DPR" which stands for Dense Passage Retrieval.

I hope this can help any further readers who do not struggle with what "DRP" is.

**Comment by jacklin64** [comment]
Hi @ArtemisDicoTiar, thanks for reading our paper. Welcome any suggestion!
