### ISSUE TITLE
What is QRELS_PATH in the https://github.com/castorini/dhr/blob/main/docs/dhr/msmarco-passage-train-eval.md?

### ISSUE THREAD

**Issue by shizhl** [castorini/dhr#2]

**Comment by jacklin64** [comment]
Hi @shizhl, thanks for the question. You can go to the official website (https://microsoft.github.io/msmarco/Datasets) to download the qrel file for passage ranking. And in the readme, we evaluate in the dev set and the corresponding eval file is here https://msmarco.blob.core.windows.net/msmarcoranking/qrels.dev.tsv.
